# Generated by Django 3.2.16 on 2026-05-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє')),
                ('description', models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('slug', models.SlugField(unique=True, verbose_name='РРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ')),
                ('is_published', models.BooleanField(default=True, verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ')),
            ],
            options={
                'verbose_name': 'РљР°С‚РµРіРѕСЂРёСЏ',
                'verbose_name_plural': 'РљР°С‚РµРіРѕСЂРёРё',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('is_published', models.BooleanField(default=True, verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ')),
            ],
            options={
                'verbose_name': 'Р›РѕРєР°С†РёСЏ',
                'verbose_name_plural': 'Р›РѕРєР°С†РёРё',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє')),
                ('text', models.TextField(verbose_name='РўРµРєСЃС‚')),
                ('pub_date', models.DateTimeField(verbose_name='Р”Р°С‚Р° Рё РІСЂРµРјСЏ РїСѓР±Р»РёРєР°С†РёРё')),
                ('is_published', models.BooleanField(default=True, verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='РђРІС‚РѕСЂ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='РљР°С‚РµРіРѕСЂРёСЏ')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='Р›РѕРєР°С†РёСЏ')),
            ],
            options={
                'verbose_name': 'РџСѓР±Р»РёРєР°С†РёСЏ',
                'verbose_name_plural': 'РџСѓР±Р»РёРєР°С†РёРё',
                'ordering': ['-pub_date'],
            },
        ),
    ]
