# Generated by Django 3.2.16 on 2026-05-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'РєР°С‚РµРіРѕСЂРёСЏ', 'verbose_name_plural': 'РљР°С‚РµРіРѕСЂРёРё'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'РјРµСЃС‚РѕРїРѕР»РѕР¶РµРЅРёРµ', 'verbose_name_plural': 'РњРµСЃС‚РѕРїРѕР»РѕР¶РµРЅРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'РїСѓР±Р»РёРєР°С†РёСЏ', 'verbose_name_plural': 'РџСѓР±Р»РёРєР°С†РёРё'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”РѕР±Р°РІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='РЎРЅРёРјРёС‚Рµ РіР°Р»РѕС‡РєСѓ, С‡С‚РѕР±С‹ СЃРєСЂС‹С‚СЊ РїСѓР±Р»РёРєР°С†РёСЋ.', verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='РРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ СЃС‚СЂР°РЅРёС†С‹ РґР»СЏ URL; СЂР°Р·СЂРµС€РµРЅС‹ СЃРёРјРІРѕР»С‹ Р»Р°С‚РёРЅРёС†С‹, С†РёС„СЂС‹, РґРµС„РёСЃ Рё РїРѕРґС‡С‘СЂРєРёРІР°РЅРёРµ.', unique=True, verbose_name='РРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”РѕР±Р°РІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True, help_text='РЎРЅРёРјРёС‚Рµ РіР°Р»РѕС‡РєСѓ, С‡С‚РѕР±С‹ СЃРєСЂС‹С‚СЊ РїСѓР±Р»РёРєР°С†РёСЋ.', verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, verbose_name='РќР°Р·РІР°РЅРёРµ РјРµСЃС‚Р°'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='РђРІС‚РѕСЂ РїСѓР±Р»РёРєР°С†РёРё'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='РљР°С‚РµРіРѕСЂРёСЏ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”РѕР±Р°РІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='РЎРЅРёРјРёС‚Рµ РіР°Р»РѕС‡РєСѓ, С‡С‚РѕР±С‹ СЃРєСЂС‹С‚СЊ РїСѓР±Р»РёРєР°С†РёСЋ.', verbose_name='РћРїСѓР±Р»РёРєРѕРІР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='РњРµСЃС‚РѕРїРѕР»РѕР¶РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Р•СЃР»Рё СѓСЃС‚Р°РЅРѕРІРёС‚СЊ РґР°С‚Сѓ Рё РІСЂРµРјСЏ РІ Р±СѓРґСѓС‰РµРј вЂ” РјРѕР¶РЅРѕ РґРµР»Р°С‚СЊ РѕС‚Р»РѕР¶РµРЅРЅС‹Рµ РїСѓР±Р»РёРєР°С†РёРё.', verbose_name='Р”Р°С‚Р° Рё РІСЂРµРјСЏ РїСѓР±Р»РёРєР°С†РёРё'),
        ),
    ]
